package lubin.guitar.Files;

public enum DialogType {
    CHANGE_TEACHER_PASS,
    CHANGE_TEACHER_NAME,
    FILE_DIALOG_NORMAL,
    FILE_DIALOG_MULTI,
    CHOICE_USER_ACCOUNT,
    NEW_USER,
    ERASE_USER,
    CONFIRM_ERASE_USER
}
